name = "binwoken"
main = "index.js"
compatibility_date = "2026-04-01"

[[d1_databases]]
binding = "DB"
database_name = "binwoken"
database_id = "31f18fcd-376a-4d79-a94c-6300aca38a61"

[assets]
directory = "./assets"
binding = "ASSETS"

[[queues.producers]]
binding = "SERVERFINDER_QUEUE"
queue = "serverfinder-refresh"

[[queues.consumers]]
queue = "serverfinder-refresh"
max_batch_size = 1
